### ISSUE TITLE
Shouldn't the 4 arrow buttons be programmed as a pov hat? Is there a way to do that?

### ISSUE THREAD

**Issue by Jackinator675** [BinaryMan32/phoenix-arduino#1]
Shouldn't the 4 arrow buttons be programmed as a pov hat? Is there a way to do that? I'd like to use this template to modify my own controller, but it seems like those 4 red arrow buttons on the end of the arm should be a pov hat.

**Comment by BinaryMan32** [comment]
I agree completely, and I've already implemented this. Please take a look at a56efee85180f14b54b3d86505a40519486dda27 and search for `VIRTUAL_HAT`.

I didn't update the screenshot after I added this functionality, so I can see why you'd think it wasn't implemented.

This isn't commented particularly well, but the basic idea is that `button_hat_lut` is a lookup table which converts the 4 buttons to a direction 0...7 * 45 degrees.

Note that the portion of the `sHidDescriptorData` which defines the hat was already present, so you'll want to look for where I changed from `#if 0` to `#if VIRTUAL_HAT`.

Let me know if it helps you!

**Comment by Jackinator675** [comment]
Thank you for that clarification.
